### ISSUE TITLE
[Development build]Unable to recenter view

### ISSUE THREAD

**Issue by sycspysycspy** [fholger/crysis_vrmod#10]
Thanks for the mod. As always, very impressive work. 
I tried the development build. I tried everything I could, recenter from the steamvr, recenter from my headset, but the camera is still around 50cm above my character. This dosen't seem to be a problem in 0.1.2, but I found that the aiming is hard with even with slight head movement, the ball is not on target any more, hope we could get  room scale and motion controller support one day.

**Comment by fholger** [comment]
With SteamVR, you need to select "Recalibrate seated position" from SteamVR's *desktop* menu. The in-VR view calibration unfortunately does not work in OpenXR. That's a bug in SteamVR, can't really do anything about that.

**Comment by huliqan** [comment]
in v0.2.0 it dos not works with OpenXR .How to recenter now ?( in SteamVR now not centeribg)

**Comment by fholger** [comment]
I explained it in the answer above yours. You need to go with the "Reset seated position" in SteamVR's desktop menu. It does not work from within VR.

**Comment by huliqan** [comment]
Ok! I found it on monitor,yaeh !)
thanks

**Comment by sycspysycspy** [comment]
As what @fholger said, use the "Reset seated position" in the SteamVR on the desktop(monitor). Problem solved.
