### ISSUE TITLE
Windows defender just flagged the crysis-vrmod-0.1.0.exe file as having the trojan wacatac.b ml

### ISSUE THREAD

**Issue by hundenmarvin** [fholger/crysis_vrmod#2]
Do I just ignore or what?

**Comment by fholger** [comment]
That's up to you, really.
All I can tell you is that the source code is available for you or someone else to study and that the executables are built right here on Github servers, not even on my own machine.

**Comment by hundenmarvin** [comment]
Sounds good. Let´s play some Crysis   []-)
