### ISSUE TITLE
Change graphics resolution to native HMD 

### ISSUE THREAD

**Issue by mfl3x** [fholger/crysis_vrmod#21]
Hey mate, did I miss settings changes for graphics resolution somewhere (cant change in game for reasons unknown) or is this a manual change only? Took me a day to figure out which cfg file to change the vid resolution to pico 4 specs and now got crysis running at 2160x2160p native res. Looks incredible and alien ship is hands down one of the best VR experiences Ive had. Want to add instructions on how to change?

**Comment by fholger** [comment]
The VR render resolution is governed by your VR runtime and must be set there. In case of the Pico, it's probably SteamVR, so you'll have to change via the SteamVR graphics settings. Editing the game's cfg files will *not* change the VR resolution, only (potentially) the mirror window size.

**Comment by mfl3x** [comment]
Yep youre right doesnt change in game resolution. Thanks for the assist as always.
