### ISSUE TITLE
Windows 11 black screen

### ISSUE THREAD

**Issue by Wokgui** [fholger/crysis_vrmod#26]
Hi,

I installed Crysis and the VR mod on Windows 11 but I have a black screen when I click on crysisvr and then nothing happens. I saw in another discussion that it may be openxr toolkit, but I don't have it installed.
Could you please help me ?

Thanks !

Here is the Crysis game.log :

BackupNameAttachment=" Build(6156) Date(04 Nov 2023) Time(22 13 44)"  -- used by backup system
 
Log Started at Saturday, November 04, 2023 22:13:44
Running 64 bit version
Executable: F:\SteamLibrary\steamapps\common\Crysis\Bin64\CrysisVR.exe
FileVersion: 1.1.1.6156
ProductVersion: 1.1.1.6156
Using STLport C++ Standard Library implementation
 
Added MOD directory <Mods\VRMod\> to CryPak
C1-Launcher Game v3 64-bit
13th Gen Intel(R) Core(TM) i7-13700F [Count: 24] [Features: MMX SSE SSE2]
Windows 64 bit (build 6.2.9200)
System language: French
Windows Directory: "C:\WINDOWS"
Prerequisites...
* Installation of KB940105 hotfix required: no! (either not needed or already installed)
Local time is 22:13:44 11/04/23, system running for 147 minutes
32604MB physical memory installed, 23145MB available, 134217727MB virtual memory installed, 29 percent of memory in use
PageFile usage: 37MB, Working Set: 15MB, Peak PageFile usage: 37MB,
Current display mode is 3440x1440x32, (Unknown graphics card)
IBM enhanced (101/102-key) keyboard and 16+ button mouse installed
--------------------------------------------------------------------------------
Stream Engine Initialization
Localized language content(english) not available or modified from the original installation.
Network initialization
[net] using iocp socket io management
Physics initialization
MovieSystem initialization
Renderer initialization
================================ CRASH DETECTED ================================
C1-Launcher Game v3 64-bit
Access violation exception (0xC0000005) at 0x00000000380C7442
Read from 0x0000000000000119 failed
Physical memory = 32603.7 MiB (23042.8 MiB available, 29.3% used)
Virtual memory = 134217727.9 MiB (134213121.0 MiB available, 0.0% used)
Registers:
RIP: 00000000380C7442 RSP: 000000000014DA70 RBP: 0000000016010631 EFLAGS: 00010206
RAX: 0000000000000001 RBX: 0000000000010010 RCX: 00007FFDB37AB414 RDX: 0000000000000000
RSI: 0000000000000001 RDI: 0000000002BC50D0 R8:  000000000014DA38 R9:  0000000000000000
R10: 0000000000000000 R11: 0000000000000246 R12: 00000000060D4658 R13: 0000000000000000
R14: 0000000000000001 R15: FFFFFFFFFFFFFFFF
Callstack:
00000000380C7442: ?? () in CryRenderD3D10.dll
00000000381C4A64: ?? () in CryRenderD3D10.dll
00000000381C5042: ?? () in CryRenderD3D10.dll
00000000381C63A8: ?? () in CryRenderD3D10.dll
00000000380C91CB: ?? () in CryRenderD3D10.dll
00000000380C9749: ?? () in CryRenderD3D10.dll
0000000036542DA0: ?? () in CrySystem.dll
0000000036546990: ?? () in CrySystem.dll
0000000036522962: ?? () in CrySystem.dll
0000000030828729: ?? () in CryAction.dll
00000000390036AA: ?? () in CryGame.dll
000000003900609B: ?? () in CryGame.dll
0000000140003B0A: ?? () in CrysisVR.exe
00000001400018FC: ?? () in CrysisVR.exe
0000000140001A2E: ?? () in CrysisVR.exe
0000000140005F36: ?? () in CrysisVR.exe
00007FFDB50C257D: ?? () in KERNEL32.DLL
00007FFDB636AA58: ?? () in ntdll.dll
Modules (107):
00000000022D0000 - 0000000002306000 C:\WINDOWS\SYSTEM32\dxcore.dll
0000000030500000 - 00000000309A0000 F:\SteamLibrary\steamapps\common\Crysis\Bin64\CryAction.dll
0000000034000000 - 000000003403F000 F:\SteamLibrary\steamapps\common\Crysis\Bin64\CryMovie.dll
0000000035000000 - 0000000035451000 F:\SteamLibrary\steamapps\common\Crysis\Bin64\CryPhysics.dll
0000000036500000 - 00000000367FC000 F:\SteamLibrary\steamapps\common\Crysis\Bin64\CrySystem.dll
0000000038000000 - 0000000038A9E000 F:\SteamLibrary\steamapps\common\Crysis\Bin64\CryRenderD3D10.dll
0000000039000000 - 000000003947A000 F:\SteamLibrary\steamapps\common\Crysis\Bin64\CryGame.dll
0000000039500000 - 0000000039741000 F:\SteamLibrary\steamapps\common\Crysis\Bin64\CryNetwork.dll
000000006B6F0000 - 000000006B76D000 C:\WINDOWS\SYSTEM32\d3dx10_34.dll
000000006B770000 - 000000006B839000 C:\WINDOWS\WinSxS\amd64_microsoft.vc80.crt_1fc8b3b9a1e18e3b_8.0.50727.9680_none_88e394a52fab6222\MSVCR80.dll
000000006B840000 - 000000006BC51000 F:\SteamLibrary\steamapps\common\Crysis\Mods\VRMod\Bin64\VRMod.dll
0000000140000000 - 000000014003B000 F:\SteamLibrary\steamapps\common\Crysis\Bin64\CrysisVR.exe
0000000180000000 - 000000018001A000 F:\SteamLibrary\steamapps\common\Crysis\Bin64\CompressATI2.dll
00007FFD516F0000 - 00007FFD519C1000 C:\WINDOWS\system32\nvspcap64.dll
00007FFD60C20000 - 00007FFD60D58000 C:\WINDOWS\system32\d3d10.dll
00007FFD68160000 - 00007FFD685A5000 C:\WINDOWS\SYSTEM32\UIAutomationCore.DLL
00007FFD76E10000 - 00007FFD76E5E000 C:\Windows\System32\Windows.Internal.Graphics.Display.DisplayColorManagement.dll
00007FFD7A4A0000 - 00007FFD7A4A9000 C:\WINDOWS\SYSTEM32\WSOCK32.dll
00007FFD84A50000 - 00007FFD84AFB000 C:\Windows\System32\OneCoreCommonProxyStub.dll
00007FFD84E80000 - 00007FFD84EA1000 C:\WINDOWS\system32\nlansp_c.dll
00007FFD84EB0000 - 00007FFD84EC1000 C:\WINDOWS\System32\winrnr.dll
00007FFD84ED0000 - 00007FFD84EEB000 C:\WINDOWS\system32\pnrpnsp.dll
00007FFD84F60000 - 00007FFD84F77000 C:\WINDOWS\system32\napinsp.dll
00007FFD90960000 - 00007FFD95D6B000 C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_8f4dab92e290c42d\nvwgf2umx.dll
00007FFD99DE0000 - 00007FFD9A517000 C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_8f4dab92e290c42d\Display.NvContainer\MessageBus.dll
00007FFD9CC80000 - 00007FFD9D422000 C:\WINDOWS\SYSTEM32\nvapi64.dll
00007FFD9D7E0000 - 00007FFD9D86E000 C:\WINDOWS\SYSTEM32\MSVCP140.dll
00007FFD9D870000 - 00007FFD9D87C000 C:\WINDOWS\SYSTEM32\VCRUNTIME140_1.dll
00007FFD9D880000 - 00007FFD9D89B000 C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll
00007FFD9E960000 - 00007FFD9EA1C000 C:\WINDOWS\SYSTEM32\mscms.dll
00007FFD9F5A0000 - 00007FFD9F5BE000 C:\WINDOWS\SYSTEM32\MSACM32.dll
00007FFD9F630000 - 00007FFD9F65B000 C:\WINDOWS\SYSTEM32\MSVFW32.dll
00007FFD9F660000 - 00007FFD9F684000 C:\WINDOWS\SYSTEM32\AVIFIL32.dll
00007FFD9F690000 - 00007FFD9F6C7000 C:\WINDOWS\SYSTEM32\d3d10_1.dll
00007FFD9FEB0000 - 00007FFD9FFFA000 C:\WINDOWS\SYSTEM32\textinputframework.dll
00007FFDA0690000 - 00007FFDA287D000 C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_8f4dab92e290c42d\nvgpucomp64.dll
00007FFDA28A0000 - 00007FFDA2AD3000 C:\WINDOWS\SYSTEM32\dbghelp.dll
00007FFDA33E0000 - 00007FFDA3414000 C:\WINDOWS\SYSTEM32\WINMM.dll
00007FFDA4E60000 - 00007FFDA4EC9000 C:\WINDOWS\system32\Oleacc.dll
00007FFDA4ED0000 - 00007FFDA5163000 C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.22621.2506_none_270c5ae97388e100\COMCTL32.dll
00007FFDA7260000 - 00007FFDA731C000 C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_8f4dab92e290c42d\nvldumdx.dll
00007FFDA7C20000 - 00007FFDA8245000 C:\Windows\System32\OneCoreUAPCommonProxyStub.dll
00007FFDA86C0000 - 00007FFDA8818000 C:\WINDOWS\SYSTEM32\drvstore.dll
00007FFDA8EA0000 - 00007FFDA8ED2000 C:\WINDOWS\SYSTEM32\cryptnet.dll
00007FFDAA770000 - 00007FFDAA7F3000 C:\WINDOWS\System32\fwpuclnt.dll
00007FFDAA800000 - 00007FFDAAB6C000 C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
00007FFDAB2C0000 - 00007FFDAB7B4000 C:\WINDOWS\SYSTEM32\WININET.dll
00007FFDABF90000 - 00007FFDABFAF000 C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
00007FFDAC200000 - 00007FFDAC24A000 C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll
00007FFDACD10000 - 00007FFDACD25000 C:\WINDOWS\system32\wshbth.dll
00007FFDAD360000 - 00007FFDAD36A000 C:\WINDOWS\SYSTEM32\VERSION.dll
00007FFDAD9F0000 - 00007FFDAD9FA000 C:\Windows\System32\rasadhlp.dll
00007FFDAF5F0000 - 00007FFDAF847000 C:\WINDOWS\SYSTEM32\d3d11.dll
00007FFDAFE40000 - 00007FFDB0092000 C:\WINDOWS\SYSTEM32\dcomp.dll
00007FFDB00A0000 - 00007FFDB00AE000 C:\WINDOWS\SYSTEM32\d3d10core.dll
00007FFDB01D0000 - 00007FFDB01DE000 C:\WINDOWS\SYSTEM32\d3d10_1core.dll
00007FFDB0610000 - 00007FFDB0743000 C:\WINDOWS\SYSTEM32\CoreMessaging.dll
00007FFDB0B40000 - 00007FFDB0BEB000 C:\WINDOWS\system32\uxtheme.dll
00007FFDB0D10000 - 00007FFDB0E08000 C:\WINDOWS\SYSTEM32\dxgi.dll
00007FFDB0F10000 - 00007FFDB0F3B000 C:\WINDOWS\SYSTEM32\dwmapi.dll
00007FFDB1470000 - 00007FFDB15AE000 C:\WINDOWS\SYSTEM32\wintypes.dll
00007FFDB15C0000 - 00007FFDB1EB4000 C:\WINDOWS\SYSTEM32\windows.storage.dll
00007FFDB21D0000 - 00007FFDB21FD000 C:\WINDOWS\SYSTEM32\iphlpapi.dll
00007FFDB2200000 - 00007FFDB22F9000 C:\WINDOWS\SYSTEM32\DNSAPI.dll
00007FFDB26E0000 - 00007FFDB2715000 C:\WINDOWS\system32\rsaenh.dll
00007FFDB2720000 - 00007FFDB2738000 C:\WINDOWS\SYSTEM32\kernel.appcore.dll
00007FFDB27A0000 - 00007FFDB27D4000 C:\WINDOWS\SYSTEM32\ntmarta.dll
00007FFDB29E0000 - 00007FFDB2A22000 C:\WINDOWS\SYSTEM32\SspiCli.dll
00007FFDB2C00000 - 00007FFDB2C69000 C:\WINDOWS\SYSTEM32\MSWSOCK.DLL
00007FFDB2E50000 - 00007FFDB2E6B000 C:\WINDOWS\SYSTEM32\CRYPTSP.dll
00007FFDB2E70000 - 00007FFDB2E7C000 C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
00007FFDB2F00000 - 00007FFDB2F4B000 C:\WINDOWS\SYSTEM32\wldp.dll
00007FFDB3020000 - 00007FFDB3048000 C:\WINDOWS\SYSTEM32\bcrypt.dll
00007FFDB3330000 - 00007FFDB3342000 C:\WINDOWS\SYSTEM32\msasn1.dll
00007FFDB3350000 - 00007FFDB337C000 C:\WINDOWS\SYSTEM32\devobj.dll
00007FFDB3380000 - 00007FFDB33CE000 C:\WINDOWS\SYSTEM32\cfgmgr32.dll
00007FFDB35C0000 - 00007FFDB35E6000 C:\WINDOWS\SYSTEM32\profapi.dll
00007FFDB3690000 - 00007FFDB372A000 C:\WINDOWS\System32\msvcp_win.dll
00007FFDB3730000 - 00007FFDB379C000 C:\WINDOWS\System32\wintrust.dll
00007FFDB37A0000 - 00007FFDB37C6000 C:\WINDOWS\System32\win32u.dll
00007FFDB37D0000 - 00007FFDB38E1000 C:\WINDOWS\System32\ucrtbase.dll
00007FFDB38F0000 - 00007FFDB3A56000 C:\WINDOWS\System32\CRYPT32.dll
00007FFDB3A60000 - 00007FFDB3B79000 C:\WINDOWS\System32\gdi32full.dll
00007FFDB3B80000 - 00007FFDB3F27000 C:\WINDOWS\System32\KERNELBASE.dll
00007FFDB3F30000 - 00007FFDB3FAA000 C:\WINDOWS\System32\bcryptPrimitives.dll
00007FFDB4070000 - 00007FFDB40A1000 C:\WINDOWS\System32\IMM32.DLL
00007FFDB40B0000 - 00007FFDB4157000 C:\WINDOWS\System32\msvcrt.dll
00007FFDB4160000 - 00007FFDB4168000 C:\WINDOWS\System32\PSAPI.DLL
00007FFDB4190000 - 00007FFDB49E9000 C:\WINDOWS\System32\SHELL32.dll
00007FFDB49F0000 - 00007FFDB4AA0000 C:\WINDOWS\System32\ADVAPI32.dll
00007FFDB4AA0000 - 00007FFDB4E29000 C:\WINDOWS\System32\combase.dll
00007FFDB4F30000 - 00007FFDB4FA1000 C:\WINDOWS\System32\WS2_32.dll
00007FFDB4FB0000 - 00007FFDB50A3000 C:\WINDOWS\System32\SHCORE.dll
00007FFDB50B0000 - 00007FFDB5174000 C:\WINDOWS\System32\KERNEL32.DLL
00007FFDB5180000 - 00007FFDB5257000 C:\WINDOWS\System32\OLEAUT32.dll
00007FFDB5340000 - 00007FFDB54EE000 C:\WINDOWS\System32\USER32.dll
00007FFDB5740000 - 00007FFDB5749000 C:\WINDOWS\System32\NSI.dll
00007FFDB5760000 - 00007FFDB5810000 C:\WINDOWS\System32\clbcatq.dll
00007FFDB5810000 - 00007FFDB5839000 C:\WINDOWS\System32\GDI32.dll
00007FFDB5840000 - 00007FFDB589E000 C:\WINDOWS\System32\SHLWAPI.dll
00007FFDB58A0000 - 00007FFDB59B7000 C:\WINDOWS\System32\RPCRT4.dll
00007FFDB5A30000 - 00007FFDB5B7F000 C:\WINDOWS\System32\MSCTF.dll
00007FFDB5B80000 - 00007FFDB5D20000 C:\WINDOWS\System32\ole32.dll
00007FFDB5D20000 - 00007FFDB5DC6000 C:\WINDOWS\System32\sechost.dll
00007FFDB5E30000 - 00007FFDB62A4000 C:\WINDOWS\System32\SETUPAPI.dll
00007FFDB62B0000 - 00007FFDB62CF000 C:\WINDOWS\System32\imagehlp.dll
00007FFDB6310000 - 00007FFDB6527000 C:\WINDOWS\SYSTEM32\ntdll.dll
Command line:
"F:\SteamLibrary\steamapps\common\Crysis\Bin64\CrysisVR.exe" 
================================================================================

Thanks !

**Comment by huliqan** [comment]
it issue with new NVIDIA drivers! With old 531.41 works

**Comment by Wokgui** [comment]
Thanks !
So this mod won't be used anymore since it is important to update drivers..

**Comment by huliqan** [comment]
I roolback driver to 531.41 any time,when I want to play CrysysVR. it 2 min to time so very quickly!

**Comment by fholger** [comment]
See https://github.com/fholger/crysis_vrmod/releases/tag/v0.3.1
