### ISSUE TITLE
Access violation exception crashes game

### ISSUE THREAD

**Issue by dvngnt** [fholger/crysis_vrmod#7]
It appears the game crashes on my system upon checkpoint or after quick-saving.
I tried to reproduce this by running the executable directly without the mod and I was able to get to the first three enemies which I'm unable to do using the mod.

Other than the crashes the mod runs well 

[Game.log](https://github.com/fholger/crysis_vrmod/files/11184210/Game.log)

**Comment by dvngnt** [comment]
after disabling AA, the crashes stopped. might have to do more testing to confirm, but I'm unable to reproduce

**Comment by fholger** [comment]
Oh yeah, I remember I had crashes, too, when setting AA to 4x or higher. I can run on 2x, though.
The way AA is implemented in Crysis is a bit particular, will have to investigate some more what it's actually doing that might cause issues.
